import * as icon from "react-icons/fa";

// % % % % % % *EDUCTION PAGE* % % % % % %

// ========================================
// EDUCATION HOME - Schools , colleges & Uni
// ========================================
export const categories = [
    { title: "Explore School", description: "Explore top-rated schools offering excellent primary and secondary education with strong foundations.", icon: <icon.FaSchool className="icons" />, btn: "Visit Schools", link: "schools" },
    { title: "College's List", description: "Find the best colleges that prepare students for higher learning, skill development, and innovation.", icon: <icon.FaRegBuilding className="icons" />, btn: "Visit colleges", link: "colleges" },
    { title: "Universities", description: "Discover globally recognized universities offering advanced degrees and research opportunities.", icon: <icon.FaUniversity className="icons" />, btn: "Visit Universities", link: "uni" },
];

// ========================================
// EDUCATION HOME - Online Courses & Tutors
// ========================================
export const OtherResources = [
    { title: "Online Courses", description: "Explore top-rated courses offering excellent primary and secondary skills with strong foundations and high scope in future.", icon: <icon.FaNetworkWired className="icons" />, btn: "Online Courses", link: "onlineCourses" },
    { title: "Tutor Listing", description: "Find the best colleges that prepare students for higher learning, skill development, and innovation.", icon: <icon.FaChalkboardTeacher className="icons" />, btn: "Tutor List", link: "tutors" },
    { title: "Online Training", description: "Discover globally recognized universities offering advanced degrees and research opportunities.", icon: <icon.FaUniversity className="icons" />, btn: "Trainings", link: "onlineTraining" },
];

// &&&&&&&&&&&& *SCHOOLS DATA* &&&&&&&&&&&& \\

/* ================================
   SCHOOLS List & Links
================================ */
export const Schools = [
    { SchoolName: "Bright Future School", id: 1 },
    { SchoolName: "GreenField Public School", id: 2 },
    { SchoolName: "CityStar Academy", id: 3 },
    { SchoolName: "Unity Grammar School", id: 4 },
    { SchoolName: "SilverOak School System", id: 5 },
    { SchoolName: "Modern Vision School", id: 6 },
    { SchoolName: "Crescent High School", id: 7 }
];

// ========================================
// SCHOOLS CARD DATA
// ========================================
export const ScoolCardDta = [
    { img: "https://images.pexels.com/photos/256395/pexels-photo-256395.jpeg?auto=compress&cs=tinysrgb&w=600", InstName: "Bright Future School", Desc: "A modern learning environment focused on academics and character building.", id: "1", btn_txt: "Read More" },
    { img: "https://images.pexels.com/photos/5896843/pexels-photo-5896843.jpeg", InstName: "GreenField Public School", Desc: "Known for disciplined education and a balanced curriculum.", id: "2", btn_txt: "Read More" },
    { img: "https://images.pexels.com/photos/256491/pexels-photo-256491.jpeg?auto=compress&cs=tinysrgb&w=600", InstName: "CityStar Academy", Desc: "Top-rated academy offering strong academic programs and activities.", id: "3", btn_txt: "Read More" },
    { img: "https://images.pexels.com/photos/289738/pexels-photo-289738.jpeg?auto=compress&cs=tinysrgb&w=600", InstName: "Unity Grammar School", Desc: "Focused on discipline, academic excellence, and student development.", id: "4", btn_txt: "Read More" },
    { img: "https://images.pexels.com/photos/2305095/pexels-photo-2305095.jpeg", InstName: "SilverOak School System", Desc: "A reputable system offering advanced classroom learning.", id: "5", btn_txt: "Read More" },
    { img: "https://images.pexels.com/photos/207669/pexels-photo-207669.jpeg?auto=compress&cs=tinysrgb&w=600", InstName: "Modern Vision School", Desc: "Highly equipped school with a focus on modern education methods.", id: "6", btn_txt: "Read More" },
    { img: "https://images.pexels.com/photos/12896161/pexels-photo-12896161.jpeg", InstName: "Crescent High School", Desc: "Providing a strong academic foundation with co-curricular activities.", id: "7", btn_txt: "Read More" }
];

// ========================================
// SCHOOL'S DETAILS ARRAY
// ========================================
export const School_Details = [
    { id: 1, type: "School", name: "Bright Future School", tagline: "Shaping young minds for a bright tomorrow.", about: "Bright Future School is committed to providing a safe, nurturing, and intellectually stimulating learning environment for every child. Our dedicated faculty focuses on developing strong academic foundations while encouraging creativity and critical thinking. We believe in shaping confident individuals through a blend of modern teaching techniques and value‑based education. With well‑equipped classrooms, advanced learning tools, and a student‑centered approach, we ensure that every learner grows to their full potential. Our mission is to empower students with the skills and mindset needed for a successful future.", aboutImage: "https://images.pexels.com/photos/207684/pexels-photo-207684.jpeg", staff: [{ name: "Mr. Adeel", subject: "Mathematics", description: "Teacher of mathematics.", image: "https://images.pexels.com/photos/14257931/pexels-photo-14257931.jpeg" }, { name: "Ms. Nadia", subject: "Science", description: "Teacher of Science.", image: "https://images.pexels.com/photos/906150/pexels-photo-906150.jpeg" }], events: [{ title: "Science Exhibition", description: "Showcase of student projects.", icon: "MdScience" }, { title: "Art Fest", description: "Celebrate creativity.", icon: "FaArtstation" }], quickInfo: { basicProfile: { name: "Bright Future School", location: "Lahore", type: "Private" }, administration: { principal: "Mrs. Saba Ali", adminOffice: "0300-1112223", phone: "042-1234567", email: "info@brightfuture.com", website: "www.brightfuture.com" }, studentsStaff: { totalStudents: "500+", totalTeachers: 30, qualification: "Masters / B.Ed", ratio: "1:16", medium: "English" }, facilities: ["Smart Classrooms", "Computer Lab", "Library", "Playground", "CCTV Security"], fees: { monthlyFee: "Rs. 3500", admissionFee: "Rs. 12,000", annualCharges: "Rs. 5,000" }, resultsPerformance: { passPercentage: "97%", topAchievers: "20+", boardResults: "Excellent" }, timings: { timing: "8:00 AM – 1:30 PM", break: "30 mins", seasonalSchedules: true }, extraActivities: ["Sports & Games", "Art & Craft", "Debates & Competitions", "Tours & Events"], parentReviews: ["Amazing environment for kids.", "Teachers are very professional.", "My child loves the school!"] }, gallery: ["https://images.pexels.com/photos/349758/pexels-photo-349758.jpeg", "https://images.pexels.com/photos/462118/pexels-photo-462118.jpeg", "https://images.pexels.com/photos/349758/pexels-photo-349758.jpeg", "https://images.pexels.com/photos/459225/pexels-photo-459225.jpeg", "https://images.pexels.com/photos/667640/pexels-photo-667640.jpeg", "https://images.pexels.com/photos/4827/pexels-photo-4827.jpeg"], contact: { email: "contact@brightfuture.com", phone: "+92 300 1234567", website: "https://www.brightfuture.com" } },
    { id: 2, type: "School", name: "GreenField Public School", tagline: "Empowering students to grow and succeed.", about: "GreenField Public School focuses on building strong character, academic excellence, and social responsibility among students. Our curriculum integrates technology, creativity, and hands‑on learning experiences to prepare students for modern challenges. With experienced teachers, supportive administration, and state‑of‑the‑art facilities, we ensure a balanced and fulfilling educational journey. Our goal is to create confident, skilled, and compassionate individuals who contribute positively to society. We promote teamwork, leadership, and continuous personal growth through a wide range of academic and co‑curricular activities.", aboutImage: "https://images.pexels.com/photos/207684/pexels-photo-207684.jpeg", staff: [{ name: "Ms. Hina", subject: "Mathematics", description: "Mathematics teacher.", image: "https://images.pexels.com/photos/14257931/pexels-photo-14257931.jpeg" }, { name: "Mr. Bilal", subject: "Science", description: "Science teacher.", image: "https://images.pexels.com/photos/906150/pexels-photo-906150.jpeg" }], events: [{ title: "Annual Sports Day", description: "Sports and teamwork celebration.", icon: "FaBaseball" }, { title: "Music Concert", description: "Showcase musical talents.", icon: "FaMusic" }], quickInfo: { basicProfile: { name: "GreenField Public School", location: "Karachi", type: "Public" }, administration: { principal: "Mr. Ahmed Raza", adminOffice: "0312-1234567", phone: "021-7654321", email: "info@greenfield.com", website: "www.greenfield.com" }, studentsStaff: { totalStudents: "600+", totalTeachers: 40, qualification: "Masters / B.Ed", ratio: "1:15", medium: "English" }, facilities: ["Smart Classrooms", "Computer Lab", "Library", "Playground"], fees: { monthlyFee: "Rs. 3000", admissionFee: "Rs. 10,000", annualCharges: "Rs. 4,000" }, resultsPerformance: { passPercentage: "95%", topAchievers: "15+", boardResults: "Very Good" }, timings: { timing: "8:30 AM – 2:00 PM", break: "40 mins", seasonalSchedules: true }, extraActivities: ["Sports & Games", "Music & Drama", "Debates & Competitions"], parentReviews: ["Supportive teachers.", "Excellent environment.", "My child enjoys learning."] }, gallery: ["https://images.pexels.com/photos/349758/pexels-photo-349758.jpeg", "https://images.pexels.com/photos/462118/pexels-photo-462118.jpeg", "https://images.pexels.com/photos/667640/pexels-photo-667640.jpeg", "https://images.pexels.com/photos/4827/pexels-photo-4827.jpeg", "https://images.pexels.com/photos/459225/pexels-photo-459225.jpeg", "https:// images.pexels.com/photos/418074/pexels-photo-418074.jpeg"], contact: { email: "contact@greenfield.com", phone: "+92 300 7654321", website: "https://www.greenfield.com" } },
    { id: 3, type: "School", name: "CityStar Academy", tagline: "Excellence in education, innovation, and leadership.", about: "CityStar Academy aims to provide a dynamic learning atmosphere where innovation meets academic excellence. Our school encourages students to think creatively, explore new ideas, and engage in meaningful learning experiences. With qualified educators, a modern curriculum, and well‑established facilities, we foster personal growth and leadership qualities. Our focus on discipline, teamwork, and practical skills helps students build a strong foundation for future success. We strive to develop curious, confident, and responsible young leaders ready to thrive in a fast‑changing world.", aboutImage: "https://images.pexels.com/photos/207684/pexels-photo-207684.jpeg", staff: [{ name: "Ms. Sana", subject: "English", description: "English teacher.", image: "https://images.pexels.com/photos/14257931/pexels-photo-14257931.jpeg" }, { name: "Mr. Omar", subject: "Science", description: "Science teacher.", image: "https://images.pexels.com/photos/906150/pexels-photo-906150.jpeg" }], events: [{ title: "Tech Fair", description: "Students showcase innovation.", icon: "MdScience" }, { title: "Drama Night", description: "Theatre performances.", icon: "FaMusic" }], quickInfo: { basicProfile: { name: "CityStar Academy", location: "Islamabad", type: "Private" }, administration: { principal: "Mr. Shahid Iqbal", adminOffice: "0300-9876543", phone: "051-1234567", email: "info@citystar.com", website: "www.citystar.com" }, studentsStaff: { totalStudents: "450+", totalTeachers: 28, qualification: "Masters / B.Ed", ratio: "1:16", medium: "English" }, facilities: ["Smart Classrooms", "Computer Lab", "Library", "Playground", "CCTV Security"], fees: { monthlyFee: "Rs. 3800", admissionFee: "Rs. 11,000", annualCharges: "Rs. 5,500" }, resultsPerformance: { passPercentage: "96%", topAchievers: "18+", boardResults: "Excellent" }, timings: { timing: "8:00 AM – 1:30 PM", break: "30 mins", seasonalSchedules: true }, extraActivities: ["Sports & Games", "Art & Craft", "Debates & Competitions", "Tours & Events"], parentReviews: ["Highly recommended.", "Teachers are excellent.", "My child feels motivated."] }, gallery: ["https://images.pexels.com/photos/459225/pexels-photo-459225.jpeg", "https://images.pexels.com/photos/667640/pexels-photo-667640.jpeg", "https://images.pexels.com/photos/349758/pexels-photo-349758.jpeg", "https://images.pexels.com/photos/462118/pexels-photo-462118.jpeg", "https://images.pexels.com/photos/4827/pexels-photo-4827.jpeg", "https://images.pexels.com/photos/418074/pexels-photo-418074.jpeg"], contact: { email: "contact@citystar.com", phone: "+92 300 1122334", website: "https://www.citystar.com" } },
    { id: 4, type: "School", name: "Unity Grammar School", tagline: "Building foundations for lifelong learning.", about: "Providing quality education with a focus on values and character, Unity Grammar School fosters moral development alongside academic growth. Our teachers use interactive and activity‑based learning to bring subjects to life, making lessons interesting and memorable. We encourage critical thinking, creativity, and community involvement through subject clubs and outreach programs. The school provides safe, modern facilities where students can explore academics, arts, and sports. We aim to prepare each child with the knowledge, skills, and values required to succeed in life and contribute positively to society.", aboutImage: "https://images.pexels.com/photos/207684/pexels-photo-207684.jpeg", staff: [{ name: "Mr. Fahad", subject: "Mathematics", description: "Mathematics teacher.", image: "https://images.pexels.com/photos/14257931/pexels-photo-14257931.jpeg" }, { name: "Ms. Hira", subject: "English", description: "English teacher.", image: "https://images.pexels.com/photos/906150/pexels-photo-906150.jpeg" }], events: [{ title: "Debate Competition", description: "Enhancing critical thinking.", icon: "FaBaseball" }, { title: "Cultural Day", description: "Celebrating diversity.", icon: "FaArtstation" }], quickInfo: { basicProfile: { name: "Unity Grammar School", location: "Peshawar", type: "Private" }, administration: { principal: "Mrs. Noreen", adminOffice: "0301-2345678", phone: "091-1234567", email: "info@unitygrammar.com", website: "www.unitygrammar.com" }, studentsStaff: { totalStudents: "520+", totalTeachers: 32, qualification: "Masters / B.Ed", ratio: "1:16", medium: "English" }, facilities: ["Smart Classrooms", "Computer Lab", "Library", "Playground"], fees: { monthlyFee: "Rs. 3600", admissionFee: "Rs. 11,000", annualCharges: "Rs. 5,000" }, resultsPerformance: { passPercentage: "97%", topAchievers: "22+", boardResults: "Excellent" }, timings: { timing: "8:00 AM – 1:00 PM", break: "30 mins", seasonalSchedules: true }, extraActivities: ["Sports & Games", "Art & Craft", "Debates & Competitions"], parentReviews: ["Great academic support.", "Friendly teachers.", "My child is very happy."] }, gallery: ["https://images.pexels.com/photos/462118/pexels-photo-462118.jpeg", "https://images.pexels.com/photos/349758/pexels-photo-349758.jpeg", "https://images.pexels.com/photos/667640/pexels-photo-667640.jpeg", "https://images.pexels.com/photos/4827/pexels-photo-4827.jpeg", "https://images.pexels.com/photos/418074/pexels-photo-418074.jpeg", "https://images.pexels.com/photos/459225/pexels-photo-459225.jpeg"], contact: { email: "contact@unitygrammar.com", phone: "+92 300 2233445", website: "https://www.unitygrammar.com" } },
    { id: 5, type: "School", name: "SilverOak School System", tagline: "Excellence in academics and extracurriculars.", about: "Encouraging students to explore, innovate, and excel, SilverOak School System blends traditional values with modern educational practices. Our experienced staff focuses on personalized learning plans to help each student reach their potential. We provide a variety of extracurricular programs from sports to arts, ensuring balanced growth for all learners. The campus offers safe, well‑maintained facilities, including labs and libraries, to support academic inquiry. Our commitment is to nurture well‑rounded, confident students prepared for higher education and life beyond school.", aboutImage: "https://images.pexels.com/photos/207684/pexels-photo-207684.jpeg", staff: [{ name: "Ms. Samina", subject: "Science", description: "Science teacher.", image: "https://images.pexels.com/photos/14257931/pexels-photo-14257931.jpeg" }, { name: "Mr. Naveed", subject: "Mathematics", description: "Mathematics teacher.", image: "https://images.pexels.com/photos/906150/pexels-photo-906150.jpeg" }], events: [{ title: "Innovation Fair", description: "Showcasing creative ideas.", icon: "MdScience" }, { title: "Sports Gala", description: "Annual sports celebration.", icon: "FaBaseball" }], quickInfo: { basicProfile: { name: "SilverOak School System", location: "Lahore", type: "Private" }, administration: { principal: "Mr. Zafar", adminOffice: "0300-3456789", phone: "042-3456789", email: "info@silveroak.com", website: "www.silveroak.com" }, studentsStaff: { totalStudents: "480+", totalTeachers: 29, qualification: "Masters / B.Ed", ratio: "1:17", medium: "English" }, facilities: ["Smart Classrooms", "Computer Lab", "Library", "Playground", "CCTV Security"], fees: { monthlyFee: "Rs. 3700", admissionFee: "Rs. 12,000", annualCharges: "Rs. 5,500" }, resultsPerformance: { passPercentage: "96%", topAchievers: "20+", boardResults: "Very Good" }, timings: { timing: "8:00 AM – 1:30 PM", break: "35 mins", seasonalSchedules: true }, extraActivities: ["Sports & Games", "Art & Craft", "Debates & Competitions"], parentReviews: ["Excellent teaching methods.", "Safe environment.", "My child enjoys school."] }, gallery: ["https://images.pexels.com/photos/349758/pexels-photo-349758.jpeg", "https://images.pexels.com/photos/462118/pexels-photo-462118.jpeg", "https://images.pexels.com/photos/667640/pexels-photo-667640.jpeg", "https://images.pexels.com/photos/4827/pexels-photo-4827.jpeg", "https://images.pexels.com/photos/459225/pexels-photo-459225.jpeg", "https://images.pexels.com/photos/418074/pexels-photo-418074.jpeg"], contact: { email: "contact@silveroak.com", phone: "+92 300 3344556", website: "https://www.silveroak.com" } },
    { id: 6, type: "School", name: "Modern Vision School", tagline: "Innovative learning for modern students.", about: "We blend technology and creativity to deliver quality education. Modern Vision School fosters a culture of inquiry, collaboration, and digital literacy to prepare students for future careers. Our curriculum emphasizes STEM learning along with arts and physical education to ensure well‑rounded growth. Teachers use project‑based learning to make lessons hands‑on and relevant. We are committed to building resilient, curious learners who are ready for the challenges of higher education and the workforce.", aboutImage: "https://images.pexels.com/photos/207684/pexels-photo-207684.jpeg", staff: [{ name: "Ms. Fatima", subject: "English", description: "English teacher.", image: "https://images.pexels.com/photos/14257931/pexels-photo-14257931.jpeg" }, { name: "Mr. Usman", subject: "Science", description: "Science teacher.", image: "https://images.pexels.com/photos/906150/pexels-photo-906150.jpeg" }], events: [{ title: "Tech Week", description: "Technology and innovation projects.", icon: "MdScience" }, { title: "Art Carnival", description: "Celebrating artistic talents.", icon: "FaArtstation" }], quickInfo: { basicProfile: { name: "Modern Vision School", location: "Faisalabad", type: "Private" }, administration: { principal: "Mr. Rehan", adminOffice: "0300-4567890", phone: "041-4567890", email: "info@modernvision.com", website: "www.modernvision.com" }, studentsStaff: { totalStudents: "430+", totalTeachers: 27, qualification: "Masters / B.Ed", ratio: "1:16", medium: "English" }, facilities: ["Smart Classrooms", "Computer Lab", "Library", "Playground", "CCTV Security"], fees: { monthlyFee: "Rs. 3600", admissionFee: "Rs. 11,000", annualCharges: "Rs. 5,000" }, resultsPerformance: { passPercentage: "95%", topAchievers: "15+", boardResults: "Very Good" }, timings: { timing: "8:30 AM – 2:00 PM", break: "30 mins", seasonalSchedules: true }, extraActivities: ["Sports & Games", "Art & Craft", "Debates & Competitions"], parentReviews: ["Modern teaching methods.", "Supportive staff.", "Child enjoys learning."] }, gallery: ["https://images.pexels.com/photos/462118/pexels-photo-462118.jpeg", "https://images.pexels.com/photos/349758/pexels-photo-349758.jpeg", "https://images.pexels.com/photos/667640/pexels-photo-667640.jpeg", "https://images.pexels.com/photos/4827/pexels-photo-4827.jpeg", "https://images.pexels.com/photos/459225/pexels-photo-459225.jpeg", "https://images.pexels.com/photos/418074/pexels-photo-418074.jpeg"], contact: { email: "contact@modernvision.com", phone: "+92 300 4455667", website: "https://www.modernvision.com" } },
    { id: 7, type: "School", name: "Crescent High School", tagline: "Leading students to excellence.", about: "We focus on academic excellence and character development. Crescent High School offers a balanced program of rigorous academics, co‑curricular activities, and community engagement to prepare students for future challenges. Our emphasis on discipline, leadership, and service builds responsible citizens. Classrooms are technology‑enabled and teachers provide individualized support to meet diverse learning needs. We nurture critical thinkers who are ready to contribute positively to society and pursue higher education with confidence.", aboutImage: "https://images.pexels.com/photos/207684/pexels-photo-207684.jpeg", staff: [{ name: "Ms. Ayesha", subject: "Mathematics", description: "Mathematics teacher.", image: "https://images.pexels.com/photos/14257931/pexels-photo-14257931.jpeg" }, { name: "Mr. Salman", subject: "Science", description: "Science teacher.", image: "https://images.pexels.com/photos/906150/pexels-photo-906150.jpeg" }], events: [{ title: "Annual Science Fair", description: "Exhibit innovative projects.", icon: "MdScience" }, { title: "Music & Drama Night", description: "Showcase talents.", icon: "FaMusic" }], quickInfo: { basicProfile: { name: "Crescent High School", location: "Multan", type: "Private" }, administration: { principal: "Mr. Tariq", adminOffice: "0300-5678901", phone: "061-5678901", email: "info@crescent.com", website: "www.crescent.com" }, studentsStaff: { totalStudents: "470+", totalTeachers: 26, qualification: "Masters / B.Ed", ratio: "1:18", medium: "English" }, facilities: ["Smart Classrooms", "Computer Lab", "Library", "Playground", "CCTV Security"], fees: { monthlyFee: "Rs. 3700", admissionFee: "Rs. 12,000", annualCharges: "Rs. 5,500" }, resultsPerformance: { passPercentage: "96%", topAchievers: "18+", boardResults: "Very Good" }, timings: { timing: "8:00 AM – 1:30 PM", break: "30 mins", seasonalSchedules: true }, extraActivities: ["Sports & Games", "Art & Craft", "Debates & Competitions"], parentReviews: ["Supportive staff.", "Great academics.", "Child enjoys learning."] }, gallery: ["https://images.pexels.com/photos/349758/pexels-photo-349758.jpeg", "https://images.pexels.com/photos/462118/pexels-photo-462118.jpeg", "https://images.pexels.com/photos/667640/pexels-photo-667640.jpeg", "https://images.pexels.com/photos/4827/pexels-photo-4827.jpeg", "https://images.pexels.com/photos/459225/pexels-photo-459225.jpeg", "https://images.pexels.com/photos/418074/pexels-photo-418074.jpeg"], contact: { email: "contact@crescent.com", phone: "+92 300 5566778", website: "https://www.crescent.com" } }
];


// &&&&&&&&&&&& *COLLEGES DATA* &&&&&&&&&&&& \\

// ========================================
// COLLEGES LIST
// ========================================
export const Colleges = [
    { CollegeName: "Frontier Science College", id: 1 },
    { CollegeName: "Kohat Model College", id: 2 },
    { CollegeName: "Superior Group of Colleges", id: 3 },
    { CollegeName: "Punjab College Kohat", id: 4 },
    { CollegeName: "ICMS Degree College", id: 5 },
    { CollegeName: "Global Degree College", id: 6 },
    { CollegeName: "Universal Science & Commerce College", id: 7 },
];

// ========================================
// COLLEGES CARD DATA
// ========================================
export const CollegeCardDta = [
    { img: "https://images.pexels.com/photos/256490/pexels-photo-256490.jpeg?auto=compress&cs=tinysrgb&w=600", InstName: "Frontier Science College", Desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.", id: "1", btn_txt: "Read More" },
    { img: "https://images.pexels.com/photos/207684/pexels-photo-207684.jpeg?auto=compress&cs=tinysrgb&w=600", InstName: "Kohat Model College", Desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.", id: "2", btn_txt: "Read More" },
    { img: "https://images.pexels.com/photos/289740/pexels-photo-289740.jpeg?auto=compress&cs=tinysrgb&w=600", InstName: "Superior Group of Colleges", Desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.", id: "3", btn_txt: "Read More" },
    { img: "https://images.pexels.com/photos/256395/pexels-photo-256395.jpeg?auto=compress&cs=tinysrgb&w=600", InstName: "Punjab College Kohat", Desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.", id: "4", btn_txt: "Read More" },
    { img: "https://images.pexels.com/photos/373488/pexels-photo-373488.jpeg?auto=compress&cs=tinysrgb&w=600", InstName: "ICMS Degree College", Desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.", id: "5", btn_txt: "Read More" },
    { img: "https://images.pexels.com/photos/934062/pexels-photo-934062.jpeg?auto=compress&cs=tinysrgb&w=600", InstName: "Global Degree College", Desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.", id: "6", btn_txt: "Read More" },
    { img: "https://images.pexels.com/photos/256457/pexels-photo-256457.jpeg?auto=compress&cs=tinysrgb&w=600", InstName: "Universal Science & Commerce College", Desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.", id: "7", btn_txt: "Read More" }
];

// ========================================
// COLLEGES DETAILS ARRAY
// ========================================
export const College_Details = [
    { id: 1, type: "College", name: "Frontier Science College", tagline: "Pioneering excellence in science education.", about: "Frontier Science College is dedicated to providing a strong foundation in science, mathematics, and technology. With experienced faculty, modern laboratories, and interactive learning environments, we encourage critical thinking and innovation among students.", aboutImage: "https://images.pexels.com/photos/256393/pexels-photo-256393.jpeg", staff: [{ name: "Dr. Imran Khan", subject: "Physics", description: "Senior physics lecturer.", image: "https://images.pexels.com/photos/356043/pexels-photo-356043.jpeg" }, { name: "Mr. Saad Ali", subject: "Chemistry", description: "Expert chemistry instructor.", image: "https://images.pexels.com/photos/414519/pexels-photo-414519.jpeg" }], events: [{ title: "Science Symposium", description: "Exploring scientific innovations.", icon: "MdScience" }, { title: "Math Olympiad", description: "Competition in mathematics.", icon: "FaCalculator" }], quickInfo: { basicProfile: { name: "Frontier Science College", location: "Kohat", type: "Private" }, administration: { principal: "Dr. Faisal Ahmed", adminOffice: "0300-1234567", phone: "092-92123456", email: "info@frontierscience.edu.pk", website: "www.frontierscience.edu.pk" }, studentsStaff: { totalStudents: "800+", totalTeachers: 40, qualification: "Masters / M.Phil", ratio: "1:20", medium: "English" }, facilities: ["Science Labs", "Computer Lab", "Library", "Playground", "CCTV"], fees: { monthlyFee: "Rs. 5000", admissionFee: "Rs. 15,000", annualCharges: "Rs. 6000" }, resultsPerformance: { passPercentage: "95%", topAchievers: "20+", boardResults: "Excellent" }, timings: { timing: "8:00 AM – 2:00 PM", break: "45 mins", seasonalSchedules: true }, extraActivities: ["Debates", "Sports", "Science Club", "Workshops"], parentReviews: ["Excellent faculty and labs.", "Modern learning approach.", "Strong focus on science education."] }, gallery: ["https://images.pexels.com/photos/256395/pexels-photo-256395.jpeg", "https://images.pexels.com/photos/207684/pexels-photo-207684.jpeg", "https://images.pexels.com/photos/301926/pexels-photo-301926.jpeg", "https://images.pexels.com/photos/880460/pexels-photo-880460.jpeg", "https://images.pexels.com/photos/159844/kids-girl-pencil-drawing-159844.jpeg", "https://images.pexels.com/photos/159866/pexels-photo-159866.jpeg"], contact: { email: "contact@frontierscience.edu.pk", phone: "+92 300 1234567", website: "https://www.frontierscience.edu.pk" } },
    { id: 2, type: "College", name: "Kohat Model College", tagline: "Quality education for a brighter future.", about: "Kohat Model College is committed to providing students with a comprehensive education that combines academics, co-curricular activities, and personal growth. Our focus is on shaping responsible and knowledgeable individuals ready to excel in higher education.", aboutImage: "https://images.pexels.com/photos/256491/pexels-photo-256491.jpeg", staff: [{ name: "Mr. Aslam Khan", subject: "Mathematics", description: "Mathematics lecturer.", image: "https://images.pexels.com/photos/1181356/pexels-photo-1181356.jpeg" }, { name: "Mr. Bilal Qureshi", subject: "Biology", description: "Expert in biology education.", image: "https://images.pexels.com/photos/356043/pexels-photo-356043.jpeg" }], events: [{ title: "Annual Sports Day", description: "Encouraging physical fitness and teamwork.", icon: "FaBaseball" }, { title: "Literary Fest", description: "Showcase of writing and debate skills.", icon: "FaBook" }], quickInfo: { basicProfile: { name: "Kohat Model College", location: "Kohat", type: "Public" }, administration: { principal: "Dr. Javed Iqbal", adminOffice: "0312-6543210", phone: "092-92123457", email: "info@kohatmodel.edu.pk", website: "www.kohatmodel.edu.pk" }, studentsStaff: { totalStudents: "750+", totalTeachers: 35, qualification: "Masters / M.Phil", ratio: "1:22", medium: "English" }, facilities: ["Science Labs", "Computer Lab", "Library", "Auditorium"], fees: { monthlyFee: "Rs. 4000", admissionFee: "Rs. 12,000", annualCharges: "Rs. 5000" }, resultsPerformance: { passPercentage: "93%", topAchievers: "15+", boardResults: "Very Good" }, timings: { timing: "8:30 AM – 2:30 PM", break: "40 mins", seasonalSchedules: true }, extraActivities: ["Sports", "Debates", "Clubs", "Workshops"], parentReviews: ["Supportive faculty.", "Good environment.", "Encourages extracurricular learning."] }, gallery: ["https://images.pexels.com/photos/3184662/pexels-photo-3184662.jpeg", "https://images.pexels.com/photos/159855/pexels-photo-159855.jpeg", "https://images.pexels.com/photos/159868/pexels-photo-159868.jpeg", "https://images.pexels.com/photos/301926/pexels-photo-301926.jpeg", "https://images.pexels.com/photos/267885/pexels-photo-267885.jpeg", "https://images.pexels.com/photos/256468/pexels-photo-256468.jpeg"], contact: { email: "contact@kohatmodel.edu.pk", phone: "+92 312 6543210", website: "https://www.kohatmodel.edu.pk" } },
    { id: 3, type: "College", name: "Superior Group of Colleges", tagline: "Empowering students for higher education.", about: "Superior Group of Colleges provides a well-rounded education combining academics, technology, and leadership skills. We focus on nurturing critical thinkers and responsible citizens through modern learning practices and co-curricular activities.", aboutImage: "https://images.pexels.com/photos/207691/pexels-photo-207691.jpeg", staff: [{ name: "Mr. Saeed Khan", subject: "Physics", description: "Physics lecturer.", image: "https://images.pexels.com/photos/414519/pexels-photo-414519.jpeg" }, { name: "Mr. Amir Shah", subject: "Chemistry", description: "Chemistry lecturer.", image: "https://images.pexels.com/photos/356043/pexels-photo-356043.jpeg" }], events: [{ title: "Science Expo", description: "Exhibition of student projects.", icon: "MdScience" }, { title: "Debate Competition", description: "Improve public speaking skills.", icon: "FaMicrophone" }], quickInfo: { basicProfile: { name: "Superior Group of Colleges", location: "Kohat", type: "Private" }, administration: { principal: "Dr. Fahad Mehmood", adminOffice: "0300-5678901", phone: "092-92123458", email: "info@superiorcollege.edu.pk", website: "www.superiorcollege.edu.pk" }, studentsStaff: { totalStudents: "900+", totalTeachers: 45, qualification: "Masters / M.Phil", ratio: "1:20", medium: "English" }, facilities: ["Science Labs", "Library", "Computer Lab", "Auditorium"], fees: { monthlyFee: "Rs. 5500", admissionFee: "Rs. 18,000", annualCharges: "Rs. 7000" }, resultsPerformance: { passPercentage: "96%", topAchievers: "25+", boardResults: "Excellent" }, timings: { timing: "8:00 AM – 2:00 PM", break: "45 mins", seasonalSchedules: true }, extraActivities: ["Clubs", "Sports", "Debates", "Workshops"], parentReviews: ["Excellent labs and library.", "Motivating faculty.", "Strong focus on leadership skills."] }, gallery: ["https://images.pexels.com/photos/3184320/pexels-photo-3184320.jpeg", "https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg", "https://images.pexels.com/photos/3184396/pexels-photo-3184396.jpeg", "https://images.pexels.com/photos/3184380/pexels-photo-3184380.jpeg", "https://images.pexels.com/photos/3184642/pexels-photo-3184642.jpeg", "https://images.pexels.com/photos/3184338/pexels-photo-3184338.jpeg"], contact: { email: "contact@superiorcollege.edu.pk", phone: "+92 300 5678901", website: "https://www.superiorcollege.edu.pk" } },
    { id: 4, type: "College", name: "Punjab College Kohat", tagline: "Inspiring academic excellence and innovation.", about: "Punjab College Kohat emphasizes holistic education that balances academics, co-curricular activities, and character development. Students are guided to achieve excellence and pursue innovative ideas for personal and professional growth.", aboutImage: "https://images.pexels.com/photos/3184328/pexels-photo-3184328.jpeg", staff: [{ name: "Mr. Arslan Raza", subject: "Mathematics", description: "Senior lecturer in mathematics.", image: "https://images.pexels.com/photos/356043/pexels-photo-356043.jpeg" }, { name: "Mr. Salman Iqbal", subject: "Physics", description: "Physics instructor.", image: "https://images.pexels.com/photos/414519/pexels-photo-414519.jpeg" }], events: [{ title: "Tech Week", description: "Showcase of student projects.", icon: "FaLaptop" }, { title: "Cultural Fest", description: "Celebrating arts and culture.", icon: "FaGlobe" }], quickInfo: { basicProfile: { name: "Punjab College Kohat", location: "Kohat", type: "Private" }, administration: { principal: "Dr. Naveed Khan", adminOffice: "0301-2233445", phone: "092-92123459", email: "info@punjabcollege.edu.pk", website: "www.punjabcollege.edu.pk" }, studentsStaff: { totalStudents: "850+", totalTeachers: 42, qualification: "Masters / M.Phil", ratio: "1:21", medium: "English" }, facilities: ["Labs", "Library", "Computer Lab", "Auditorium"], fees: { monthlyFee: "Rs. 5200", admissionFee: "Rs. 16,000", annualCharges: "Rs. 6000" }, resultsPerformance: { passPercentage: "94%", topAchievers: "18+", boardResults: "Very Good" }, timings: { timing: "8:00 AM – 2:00 PM", break: "40 mins", seasonalSchedules: true }, extraActivities: ["Debates", "Sports", "Tech Club"], parentReviews: ["Very supportive staff.", "Modern learning environment.", "Encourages student participation."] }, gallery: ["https://images.pexels.com/photos/3184380/pexels-photo-3184380.jpeg", "https://images.pexels.com/photos/3184642/pexels-photo-3184642.jpeg", "https://images.pexels.com/photos/3184338/pexels-photo-3184338.jpeg", "https://images.pexels.com/photos/3184396/pexels-photo-3184396.jpeg", "https://images.pexels.com/photos/3184320/pexels-photo-3184320.jpeg", "https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg"], contact: { email: "contact@punjabcollege.edu.pk", phone: "+92 301 2233445", website: "https://www.punjabcollege.edu.pk" } },
    { id: 5, type: "College", name: "ICMS Degree College", tagline: "Excellence and innovation in higher education.", about: "ICMS Degree College provides an environment that fosters innovation, analytical thinking, and academic success. The college emphasizes both theoretical knowledge and practical skills, preparing students for higher studies and career opportunities.", aboutImage: "https://images.pexels.com/photos/3184471/pexels-photo-3184471.jpeg", staff: [{ name: "Mr. Kamran Ali", subject: "English", description: "English language lecturer.", image: "https://images.pexels.com/photos/414519/pexels-photo-414519.jpeg" }, { name: "Mr. Asad Raza", subject: "Mathematics", description: "Expert in mathematics.", image: "https://images.pexels.com/photos/356043/pexels-photo-356043.jpeg" }], events: [{ title: "Debate Competition", description: "Enhancing communication skills.", icon: "FaMicrophone" }, { title: "Science Fair", description: "Innovative student projects.", icon: "MdScience" }], quickInfo: { basicProfile: { name: "ICMS Degree College", location: "Kohat", type: "Private" }, administration: { principal: "Dr. Shahbaz Khan", adminOffice: "0302-3344556", phone: "092-92123460", email: "info@icms.edu.pk", website: "www.icms.edu.pk" }, studentsStaff: { totalStudents: "780+", totalTeachers: 38, qualification: "Masters / M.Phil", ratio: "1:20", medium: "English" }, facilities: ["Labs", "Library", "Computer Lab", "Auditorium"], fees: { monthlyFee: "Rs. 4800", admissionFee: "Rs. 14,000", annualCharges: "Rs. 5500" }, resultsPerformance: { passPercentage: "95%", topAchievers: "20+", boardResults: "Excellent" }, timings: { timing: "8:00 AM – 2:15 PM", break: "40 mins", seasonalSchedules: true }, extraActivities: ["Debates", "Sports", "Science Club", "Workshops"], parentReviews: ["Excellent faculty.", "Good labs and resources.", "Encourages student innovation."] }, gallery: ["https://images.pexels.com/photos/3184631/pexels-photo-3184631.jpeg", "https://images.pexels.com/photos/3184396/pexels-photo-3184396.jpeg", "https://images.pexels.com/photos/3184338/pexels-photo-3184338.jpeg", "https://images.pexels.com/photos/3184320/pexels-photo-3184320.jpeg", "https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg", "https://images.pexels.com/photos/3184380/pexels-photo-3184380.jpeg"], contact: { email: "contact@icms.edu.pk", phone: "+92 302 3344556", website: "https://www.icms.edu.pk" } },
    { id: 6, type: "College", name: "Global Degree College", tagline: "Shaping global minds for tomorrow.", about: "Global Degree College is committed to providing high-quality education with a focus on research, leadership, and innovation. Students are encouraged to think critically and explore creative solutions to academic and real-life challenges.", aboutImage: "https://images.pexels.com/photos/3184631/pexels-photo-3184631.jpeg", staff: [{ name: "Mr. Faisal Raza", subject: "Economics", description: "Economics lecturer.", image: "https://images.pexels.com/photos/356043/pexels-photo-356043.jpeg" }, { name: "Mr. Ahmed Shah", subject: "Physics", description: "Physics lecturer.", image: "https://images.pexels.com/photos/414519/pexels-photo-414519.jpeg" }], events: [{ title: "Research Week", description: "Showcasing student research.", icon: "FaFlask" }, { title: "Sports Gala", description: "Promoting physical fitness.", icon: "FaFootballBall" }], quickInfo: { basicProfile: { name: "Global Degree College", location: "Kohat", type: "Private" }, administration: { principal: "Dr. Naveed Ali", adminOffice: "0303-4455667", phone: "092-92123461", email: "info@globaldegree.edu.pk", website: "www.globaldegree.edu.pk" }, studentsStaff: { totalStudents: "820+", totalTeachers: 40, qualification: "Masters / M.Phil", ratio: "1:21", medium: "English" }, facilities: ["Labs", "Library", "Computer Lab", "Auditorium"], fees: { monthlyFee: "Rs. 5000", admissionFee: "Rs. 15,000", annualCharges: "Rs. 6000" }, resultsPerformance: { passPercentage: "96%", topAchievers: "22+", boardResults: "Excellent" }, timings: { timings: "8:00 AM – 2:30 PM", break: "45 mins", seasonalSchedules: true }, extraActivities: ["Debates", "Sports", "Clubs", "Workshops"], parentReviews: ["Excellent learning environment.", "Faculty is highly qualified.", "Focus on practical learning."] }, gallery: ["https://images.pexels.com/photos/3184497/pexels-photo-3184497.jpeg", "https://images.pexels.com/photos/3184611/pexels-photo-3184611.jpeg", "https://images.pexels.com/photos/3184328/pexels-photo-3184328.jpeg", "https://images.pexels.com/photos/3184287/pexels-photo-3184287.jpeg", "https://images.pexels.com/photos/3184338/pexels-photo-3184338.jpeg", "https://images.pexels.com/photos/3184396/pexels-photo-3184396.jpeg"], contact: { email: "contact@globaldegree.edu.pk", phone: "+92 303 4455667", website: "https://www.globaldegree.edu.pk" } },
    { id: 7, type: "College", name: "Universal Science & Commerce College", tagline: "Blending science and commerce for success.", about: "Universal Science & Commerce College aims to provide a high-quality education in both science and commerce streams. Our curriculum is designed to develop analytical, technical, and leadership skills while promoting a culture of research and innovation.", aboutImage: "https://images.pexels.com/photos/3184662/pexels-photo-3184662.jpeg", staff: [{ name: "Mr. Ahsan Khan", subject: "Accounting", description: "Accounting lecturer.", image: "https://images.pexels.com/photos/414519/pexels-photo-414519.jpeg" }, { name: "Mr. Zeeshan Ali", subject: "Chemistry", description: "Chemistry lecturer.", image: "https://images.pexels.com/photos/356043/pexels-photo-356043.jpeg" }], events: [{ title: "Business Fair", description: "Showcase of student business projects.", icon: "FaBriefcase" }, { title: "Science Symposium", description: "Innovative scientific presentations.", icon: "MdScience" }], quickInfo: { basicProfile: { name: "Universal Science & Commerce College", location: "Kohat", type: "Private" }, administration: { principal: "Dr. Salman Ahmed", adminOffice: "0304-5566778", phone: "092-92123462", email: "info@universalscience.edu.pk", website: "www.universalscience.edu.pk" }, studentsStaff: { totalStudents: "870+", totalTeachers: 42, qualification: "Masters / M.Phil", ratio: "1:21", medium: "English" }, facilities: ["Labs", "Library", "Computer Lab", "Auditorium"], fees: { monthlyFee: "Rs. 5200", admissionFee: "Rs. 16,000", annualCharges: "Rs. 6000" }, resultsPerformance: { passPercentage: "95%", topAchievers: "20+", boardResults: "Excellent" }, timings: { timing: "8:00 AM – 2:30 PM", break: "45 mins", seasonalSchedules: true }, extraActivities: ["Clubs", "Debates", "Sports", "Workshops"], parentReviews: ["High-quality education.", "Experienced faculty.", "Encourages innovation and leadership."] }, gallery: ["https://images.pexels.com/photos/3184396/pexels-photo-3184396.jpeg", "https://images.pexels.com/photos/3184380/pexels-photo-3184380.jpeg", "https://images.pexels.com/photos/3184338/pexels-photo-3184338.jpeg", "https://images.pexels.com/photos/3184320/pexels-photo-3184320.jpeg", "https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg", "https://images.pexels.com/photos/3184642/pexels-photo-3184642.jpeg"], contact: { email: "contact@universalscience.edu.pk", phone: "+92 304 5566778", website: "https://www.universalscience.edu.pk" } }
];

// &&&&&&&&&&&& *UNIVERSITIES DATA* &&&&&&&&&&&& \\

// ========================================
// UNIVERSITIES LIST
// ========================================
export const Universities = [
    { UniName: "Kohat University of Science & Technology", id: 1 },
    { UniName: "University of Peshawar Kohat Campus", id: 2 },
    { UniName: "Allama Iqbal Open University Kohat", id: 3 },
    { UniName: "COMSATS University Islamabad Kohat Campus", id: 4 },
    { UniName: "Iqra National University Kohat", id: 5 },
    { UniName: "Sarhad University of Science & IT Kohat", id: 6 },
    { UniName: "Global University of Kohat", id: 7 },
];

// ========================================
// UNIVERSITIES CARD DATA
// ========================================
export const UniCardDta = [
    { img: "https://images.pexels.com/photos/2305098/pexels-photo-2305098.jpeg", InstName: "Kohat University of Science & Technology", Desc: "Leading university in Kohat offering a wide range of science and technology programs.", id: "1", btn_txt: "Read More" },
    { img: "https://images.pexels.com/photos/256541/pexels-photo-256541.jpeg", InstName: "University of Peshawar Kohat Campus", Desc: "Renowned for quality education and research, providing diverse undergraduate and postgraduate programs.", id: "2", btn_txt: "Read More" },
    { img: "https://images.pexels.com/photos/210661/pexels-photo-210661.jpeg", InstName: "Allama Iqbal Open University Kohat", Desc: "Focuses on distance learning with flexible programs and innovative educational approaches.", id: "3", btn_txt: "Read More" },
    { img: "https://images.pexels.com/photos/207691/pexels-photo-207691.jpeg", InstName: "COMSATS University Islamabad Kohat Campus", Desc: "Offers cutting-edge technology and science programs with modern labs and research facilities.", id: "4", btn_txt: "Read More" },
    { img: "https://images.pexels.com/photos/256540/pexels-photo-256540.jpeg", InstName: "Iqra National University Kohat", Desc: "Committed to academic excellence and providing a student-centered learning environment.", id: "5", btn_txt: "Read More" },
    { img: "https://images.pexels.com/photos/207691/pexels-photo-207691.jpeg", InstName: "Sarhad University of Science & IT Kohat", Desc: "Known for technology and IT programs, with experienced faculty and modern infrastructure.", id: "6", btn_txt: "Read More" },
    { img: "https://images.pexels.com/photos/2305095/pexels-photo-2305095.jpeg", InstName: "Global University of Kohat", Desc: "Offers a variety of programs in business, arts, and sciences with global exposure.", id: "7", btn_txt: "Read More" }
];

// ========================================
// UNIVERSITIES DETAILS ARRAY
// ========================================
export const Unis_Details = [
    { id: 1, type: "University", name: "Kohat University of Science & Technology", tagline: "Excellence in Science & Technology Education", about: "KUST is a premier university in Kohat offering advanced programs in science, technology, and research.", aboutImage: "https://images.pexels.com/photos/3184320/pexels-photo-3184320.jpeg", staff: [{ name: "Dr. Ahmed Khan", subject: "Computer Science", description: "Professor of CS.", image: "https://images.pexels.com/photos/356043/pexels-photo-356043.jpeg" }, { name: "Dr. Sara Malik", subject: "Biotechnology", description: "Senior biotechnology researcher.", image: "https://images.pexels.com/photos/414519/pexels-photo-414519.jpeg" }], events: [{ title: "Tech & Research Expo", description: "Showcasing innovative university research.", icon: "MdScience" }, { title: "Science Conference", description: "National-level academic conference.", icon: "FaFlask" }], quickInfo: { basicProfile: { name: "KUST", location: "Kohat", type: "Public" }, administration: { principal: "Prof. Dr. Khalid Khan", adminOffice: "092-92123450", phone: "092-92123450", email: "info@kust.edu.pk", website: "www.kust.edu.pk" }, studentsStaff: { totalStudents: "5000+", totalTeachers: 200, qualification: "PhD / M.Phil", ratio: "1:25", medium: "English" }, facilities: ["Modern Labs", "Digital Classrooms", "Library", "Sports Complex", "Hostel", "Transport"], fees: { monthlyFee: "N/A (Semester System)", admissionFee: "Rs. 20,000", annualCharges: "Rs. 10,000" }, resultsPerformance: { passPercentage: "97%", topAchievers: "100+", boardResults: "Excellent" }, timings: { timing: "8:00 AM – 3:00 PM", break: "45 mins", seasonalSchedules: true }, extraActivities: ["Research Clubs", "Tech Communities", "Sports", "Workshops"], parentReviews: ["Strong academic environment.", "Research-focused university.", "Modern facilities."] }, gallery: ["https://images.pexels.com/photos/3184320/pexels-photo-3184320.jpeg", "https://images.pexels.com/photos/301926/pexels-photo-301926.jpeg"], contact: { email: "info@kust.edu.pk", phone: "+92 921 1234567", website: "https://www.kust.edu.pk" } },
    { id: 2, type: "University", name: "University of Peshawar Kohat Campus", tagline: "Transforming Knowledge into Innovation", about: "UoP Kohat Campus provides quality education and research opportunities in arts, science, and technology.", aboutImage: "https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg", staff: [{ name: "Dr. Junaid Afridi", subject: "Mathematics", description: "Senior maths professor.", image: "https://images.pexels.com/photos/356043/pexels-photo-356043.jpeg" }, { name: "Dr. Hina Shah", subject: "Social Sciences", description: "Research specialist.", image: "https://images.pexels.com/photos/414519/pexels-photo-414519.jpeg" }], events: [{ title: "Research Symposium", description: "Academic presentations.", icon: "FaBook" }, { title: "Arts & Culture Day", description: "Celebrating diversity.", icon: "FaGlobe" }], quickInfo: { basicProfile: { name: "UoP Kohat Campus", location: "Kohat", type: "Public" }, administration: { principal: "Prof. Dr. Iqbal Wazir", adminOffice: "092-92123451", phone: "092-92123451", email: "contact@uopk.edu.pk", website: "www.uop.edu.pk" }, studentsStaff: { totalStudents: "3000+", totalTeachers: 150, qualification: "PhD / M.Phil", ratio: "1:28", medium: "English/Urdu" }, facilities: ["Computer Labs", "Library", "Seminar Halls", "Sports Facilities", "Cafeteria"], fees: { monthlyFee: "N/A (Semester System)", admissionFee: "Rs. 15,000", annualCharges: "Rs. 7,000" }, resultsPerformance: { passPercentage: "94%", topAchievers: "60+", boardResults: "Very Good" }, timings: { timing: "8:30 AM – 3:00 PM", break: "40 mins", seasonalSchedules: true }, extraActivities: ["Debates", "Sports", "Research Clubs"], parentReviews: ["Good academic support.", "Active research culture."] }, gallery: ["https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg", "https://images.pexels.com/photos/3184320/pexels-photo-3184320.jpeg"], contact: { email: "contact@uopk.edu.pk", phone: "+92 921 2345678", website: "https://www.uop.edu.pk" } },
    { id: 3, type: "University", name: "Allama Iqbal Open University Kohat", tagline: "Distance Learning with Quality", about: "AIOU Kohat offers flexible learning programs with an emphasis on access to education for all.", aboutImage: "https://images.pexels.com/photos/3184631/pexels-photo-3184631.jpeg", staff: [{ name: "Dr. Nargis Bibi", subject: "Education", description: "Distance learning specialist.", image: "https://images.pexels.com/photos/414519/pexels-photo-414519.jpeg" }, { name: "Mr. Farhan Malik", subject: "Management", description: "Management sciences lecturer.", image: "https://images.pexels.com/photos/356043/pexels-photo-356043.jpeg" }], events: [{ title: "Online Workshops", description: "Virtual learning enhancement.", icon: "FaLaptop" }, { title: "Teacher Training Sessions", description: "Improving teaching skills.", icon: "FaChalkboardTeacher" }], quickInfo: { basicProfile: { name: "AIOU Kohat", location: "Kohat", type: "Public, Distance Learning" }, administration: { principal: "Dr. Shazia Rehman", adminOffice: "092-92123452", phone: "092-92123452", email: "info@aiou.edu.pk", website: "www.aiou.edu.pk" }, studentsStaff: { totalStudents: "10,000+", totalTeachers: 80, qualification: "Masters / M.Phil", ratio: "1:50", medium: "English/Urdu" }, facilities: ["Online Platform", "Regional Library", "Workshops", "Support Services"], fees: { monthlyFee: "N/A", admissionFee: "Rs. 5,000", annualCharges: "Rs. 3,000" }, resultsPerformance: { passPercentage: "90%", topAchievers: "120+", boardResults: "Good" }, timings: { timing: "Flexible", break: "N/A", seasonalSchedules: true }, extraActivities: ["Online Seminars", "Research Projects"], parentReviews: ["Best distance learning institute.", "Affordable and flexible."] }, gallery: ["https://images.pexels.com/photos/3184631/pexels-photo-3184631.jpeg"], contact: { email: "info@aiou.edu.pk", phone: "+92 921 3456789", website: "https://www.aiou.edu.pk" } },
    { id: 4, type: "University", name: "COMSATS University Islamabad Kohat Campus", tagline: "Innovation & Research Driven Education", about: "CUI Kohat Campus is recognized for quality programs in technology, IT, and applied sciences.", aboutImage: "https://images.pexels.com/photos/3184396/pexels-photo-3184396.jpeg", staff: [{ name: "Dr. Salman Raza", subject: "Software Engineering", description: "Expert in software systems.", image: "https://images.pexels.com/photos/356043/pexels-photo-356043.jpeg" }, { name: "Dr. Uzair Khan", subject: "Biotechnology", description: "Research scientist.", image: "https://images.pexels.com/photos/414519/pexels-photo-414519.jpeg" }], events: [{ title: "Tech Expo", description: "Student innovations display.", icon: "MdScience" }, { title: "Research Week", description: "Scientific exhibitions.", icon: "FaFlask" }], quickInfo: { basicProfile: { name: "COMSATS Kohat", location: "Kohat", type: "Private" }, administration: { principal: "Dr. Imran Shah", adminOffice: "092-92123453", phone: "092-92123453", email: "info@comsats.edu.pk", website: "www.comsats.edu.pk" }, studentsStaff: { totalStudents: "4000+", totalTeachers: 180, qualification: "PhD / M.Phil", ratio: "1:22", medium: "English" }, facilities: ["Advanced Labs", "Digital Classrooms", "Auditorium", "Library"], fees: { monthlyFee: "N/A (Semester)", admissionFee: "Rs. 25,000", annualCharges: "Rs. 12,000" }, resultsPerformance: { passPercentage: "98%", topAchievers: "90+", boardResults: "Excellent" }, timings: { timing: "8:00 AM – 3:00 PM", break: "40 mins", seasonalSchedules: true }, extraActivities: ["Tech Clubs", "Sports", "Science Societies"], parentReviews: ["Highly qualified faculty.", "Excellent research environment."] }, gallery: ["https://images.pexels.com/photos/3184396/pexels-photo-3184396.jpeg"], contact: { email: "info@comsats.edu.pk", phone: "+92 921 4567890", website: "https://www.comsats.edu.pk" } },
    { id: 5, type: "University", name: "Iqra National University Kohat", tagline: "Empowering Future Leaders", about: "INU Kohat focuses on holistic education, combining academics with leadership and innovation.", aboutImage: "https://images.pexels.com/photos/3184471/pexels-photo-3184471.jpeg", staff: [{ name: "Dr. Ali Raza", subject: "Business", description: "Business management expert.", image: "https://images.pexels.com/photos/356043/pexels-photo-356043.jpeg" }, { name: "Ms. Sana Khan", subject: "IT", description: "Senior IT lecturer.", image: "https://images.pexels.com/photos/414519/pexels-photo-414519.jpeg" }], events: [{ title: "Management Week", description: "Leadership events.", icon: "FaUsers" }, { title: "Tech Fest", description: "Technology and innovation.", icon: "FaLaptop" }], quickInfo: { basicProfile: { name: "INU Kohat", location: "Kohat", type: "Private" }, administration: { principal: "Dr. Rehman Gul", adminOffice: "092-92123454", phone: "092-92123454", email: "info@inu.edu.pk", website: "www.inu.edu.pk" }, studentsStaff: { totalStudents: "3500+", totalTeachers: 130, qualification: "Masters / M.Phil / PhD", ratio: "1:27", medium: "English" }, facilities: ["Labs", "Library", "Auditoriums", "Sports Facilities", "Cafeteria"], fees: { monthlyFee: "N/A", admissionFee: "Rs. 20,000", annualCharges: "Rs. 10,000" }, resultsPerformance: { passPercentage: "92%", topAchievers: "70+", boardResults: "Very Good" }, timings: { timing: "8:00 AM – 3:00 PM", break: "40 mins", seasonalSchedules: true }, extraActivities: ["Sports", "Tech Clubs", "Business Seminars"], parentReviews: ["Good environment.", "Strong focus on leadership."] }, gallery: ["https://images.pexels.com/photos/3184471/pexels-photo-3184471.jpeg"], contact: { email: "info@inu.edu.pk", phone: "+92 921 5678901", website: "https://www.inu.edu.pk" } },
    { id: 6, type: "University", name: "Sarhad University of Science & IT Kohat", tagline: "Knowledge, Innovation, Excellence", about: "SUSIT Kohat is committed to providing quality education in IT and applied sciences with modern infrastructure.", aboutImage: "https://images.pexels.com/photos/3184611/pexels-photo-3184611.jpeg", staff: [{ name: "Dr. Faisal Qadir", subject: "Computer Science", description: "Expert in IT systems.", image: "https://images.pexels.com/photos/356043/pexels-photo-356043.jpeg" }, { name: "Ms. Ayesha Malik", subject: "Management", description: "Business lecturer.", image: "https://images.pexels.com/photos/414519/pexels-photo-414519.jpeg" }], events: [{ title: "IT Exhibition", description: "Tech showcases.", icon: "MdScience" }, { title: "Sports Day", description: "Physical fitness events.", icon: "FaFootballBall" }], quickInfo: { basicProfile: { name: "SUSIT Kohat", location: "Kohat", type: "Private" }, administration: { principal: "Dr. Tariq Wazir", adminOffice: "092-92123455", phone: "092-92123455", email: "info@susit.edu.pk", website: "www.susit.edu.pk" }, studentsStaff: { totalStudents: "4000+", totalTeachers: 150, qualification: "Masters / M.Phil", ratio: "1:26", medium: "English" }, facilities: ["IT Labs", "Library", "Digital Classrooms", "Sports Ground", "Cafeteria"], fees: { monthlyFee: "N/A", admissionFee: "Rs. 18,000", annualCharges: "Rs. 8,000" }, resultsPerformance: { passPercentage: "93%", topAchievers: "50+", boardResults: "Very Good" }, timings: { timing: "8:00 AM – 3:00 PM", break: "45 mins", seasonalSchedules: true }, extraActivities: ["Sports", "IT Clubs", "Workshops"], parentReviews: ["Modern campus.", "Very good IT faculty."] }, gallery: ["https://images.pexels.com/photos/3184611/pexels-photo-3184611.jpeg"], contact: { email: "info@susit.edu.pk", phone: "+92 921 6789012", website: "https://www.susit.edu.pk" } },
    { id: 7, type: "University", name: "Global University of Kohat", tagline: "Global Standards, Local Opportunities", about: "Global University provides quality education with international exposure and modern learning techniques.", aboutImage: "https://images.pexels.com/photos/3184287/pexels-photo-3184287.jpeg", staff: [{ name: "Dr. Aftab Khan", subject: "Management", description: "Professional management lecturer.", image: "https://images.pexels.com/photos/356043/pexels-photo-356043.jpeg" }, { name: "Ms. Rabia Ahmad", subject: "IT", description: "IT education specialist.", image: "https://images.pexels.com/photos/414519/pexels-photo-414519.jpeg" }], events: [{ title: "Global Expo", description: "International collaborations.", icon: "FaGlobe" }, { title: "Innovation Summit", description: "Student-led innovations.", icon: "MdScience" }], quickInfo: { basicProfile: { name: "Global University", location: "Kohat", type: "Private" }, administration: { principal: "Dr. Suleman Shah", adminOffice: "092-92123456", phone: "092-92123456", email: "info@globalu.edu.pk", website: "www.globalu.edu.pk" }, studentsStaff: { totalStudents: "3800+", totalTeachers: 140, qualification: "Masters / M.Phil / PhD", ratio: "1:27", medium: "English" }, facilities: ["Smart Classrooms", "Library", "Computer Labs", "Auditorium"], fees: { monthlyFee: "N/A", admissionFee: "Rs. 20,000", annualCharges: "Rs. 9,000" }, resultsPerformance: { passPercentage: "95%", topAchievers: "60+", boardResults: "Excellent" }, timings: { timing: "8:00 AM – 3:00 PM", break: "45 mins", seasonalSchedules: true }, extraActivities: ["Debates", "Sports", "Tech Club"], parentReviews: ["Modern environment.", "Good faculty.", "Highly interactive teaching methods."] }, gallery: ["https://images.pexels.com/photos/3184287/pexels-photo-3184287.jpeg"], contact: { email: "info@globalu.edu.pk", phone: "+92 921 7890123", website: "https://www.globalu.edu.pk" } }
];


// &&&&&&&&&&&& *ONLINE COURSES DATA* &&&&&&&&&&&& \\

/* ================================
   ONLINE COURSES List & Links
================================ */
export const OnlineCourses = [
    { CourseName: "Full Stack Web Development", id: 1 },
    { CourseName: "Data Science & Machine Learning", id: 2 },
    { CourseName: "UI/UX Design Fundamentals", id: 3 },
    { CourseName: "Digital Marketing Masterclass", id: 4 },
    { CourseName: "Python Programming for Beginners", id: 5 },
    { CourseName: "Cybersecurity Essentials", id: 6 },
    { CourseName: "Artificial Intelligence & Deep Learning", id: 7 }
];

// ========================================
// ONLINE COURSES CARD DATA
// ========================================
export const OnlineCourseCardDta = [
    { img: "https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg", InstName: "Full Stack Web Development", Desc: "Learn front-end & back-end development to become a full stack developer.", id: "1", btn_txt: "Enroll Now" },
    { img: "https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg", InstName: "Data Science & Machine Learning", Desc: "Master data analysis, statistics, and machine learning algorithms.", id: "2", btn_txt: "Enroll Now" },
    { img: "https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg", InstName: "UI/UX Design Fundamentals", Desc: "Design beautiful and user-friendly interfaces for web and mobile apps.", id: "3", btn_txt: "Enroll Now" },
    { img: "https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg", InstName: "Digital Marketing Masterclass", Desc: "Learn SEO, social media marketing, and advertising strategies.", id: "4", btn_txt: "Enroll Now" },
    { img: "https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg", InstName: "Python Programming for Beginners", Desc: "Start coding in Python and build real-world applications.", id: "5", btn_txt: "Enroll Now" },
    { img: "https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg", InstName: "Cybersecurity Essentials", Desc: "Learn how to secure systems, networks, and protect data online.", id: "6", btn_txt: "Enroll Now" },
    { img: "https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg", InstName: "Artificial Intelligence & Deep Learning", Desc: "Explore AI concepts, neural networks, and deep learning models.", id: "7", btn_txt: "Enroll Now" }
];

// ========================================
// ONLINE COURSES DETAILS ARRAY
// ========================================
export const OnlineCourses_Details = [
    { id: 1, Title: "Full Stack Web Development", tag_line: "“Build Complete Web Applications”", A_UsPara: "This course provides comprehensive training on both front-end and back-end web development using modern technologies.", Course_Info: [{ Duration: "6 Months", Mode: "Online", Skill_Level: "Beginner to Advanced", Languages: "HTML, CSS, JavaScript, Node.js, React" }], Facilities: ["Interactive Coding Labs", "Project-Based Learning", "Mentor Support", "Certificates"], Achievements: ["Build Portfolio Projects", "Deploy Real Applications", "Job Assistance"], Contact_Info: [{ Email: "info@fullstackcourses.com", Phone: "+92 300 1234567", website: "www.fullstackcourses.com" }] },
    { id: 2, Title: "Data Science & Machine Learning", tag_line: "“Analyze Data & Build Models”", A_UsPara: "Learn Python, data analysis, visualization, and machine learning to become a data science expert.", Course_Info: [{ Duration: "5 Months", Mode: "Online", Skill_Level: "Intermediate", Languages: "Python, R, SQL" }], Facilities: ["Hands-on Projects", "Jupyter Notebook Labs", "Mentor Guidance"], Achievements: ["Data Analysis Projects", "Predictive Models", "Industry-Ready Skills"], Contact_Info: [{ Email: "info@datasciencecourses.com", Phone: "+92 301 9876543", website: "www.datasciencecourses.com" }] },
    { id: 3, Title: "UI/UX Design Fundamentals", tag_line: "“Design Engaging Interfaces”", A_UsPara: "Focus on creating intuitive and appealing user interfaces with UX principles and design tools.", Course_Info: [{ Duration: "3 Months", Mode: "Online", Skill_Level: "Beginner", Tools: "Figma, Adobe XD, Sketch" }], Facilities: ["Design Labs", "Portfolio Projects", "Expert Mentorship"], Achievements: ["UI/UX Projects", "Portfolio Ready", "Design Certifications"], Contact_Info: [{ Email: "info@uxdesigncourses.com", Phone: "+92 302 5556677", website: "www.uxdesigncourses.com" }] },
    { id: 4, Title: "Digital Marketing Masterclass", tag_line: "“Grow Your Online Presence”", A_UsPara: "Learn all aspects of digital marketing including SEO, SEM, email campaigns, and social media strategies.", Course_Info: [{ Duration: "4 Months", Mode: "Online", Skill_Level: "Beginner to Intermediate" }], Facilities: ["Practical Assignments", "Real Campaigns", "Mentor Support"], Achievements: ["Marketing Portfolio", "Certifications", "Hands-on Campaign Experience"], Contact_Info: [{ Email: "info@digitalmarketing.com", Phone: "+92 303 1122334", website: "www.digitalmarketing.com" }] },
    { id: 5, Title: "Python Programming for Beginners", tag_line: "“Start Coding Today”", A_UsPara: "Learn Python from scratch and build practical applications, scripts, and projects.", Course_Info: [{ Duration: "2 Months", Mode: "Online", Skill_Level: "Beginner", Languages: "Python" }], Facilities: ["Coding Exercises", "Project Guidance", "Mentor Support"], Achievements: ["Mini Projects", "Practical Python Skills", "Completion Certificate"], Contact_Info: [{ Email: "info@pythoncourses.com", Phone: "+92 304 4455667", website: "www.pythoncourses.com" }] },
    { id: 6, Title: "Cybersecurity Essentials", tag_line: "“Protect Systems & Data”", A_UsPara: "Understand network security, system vulnerabilities, and data protection techniques in this essential course.", Course_Info: [{ Duration: "3 Months", Mode: "Online", Skill_Level: "Beginner to Intermediate" }], Facilities: ["Virtual Labs", "Simulated Hacking Scenarios", "Mentor Guidance"], Achievements: ["Security Projects", "Hands-on Experience", "Certification Provided"], Contact_Info: [{ Email: "info@cybersecurity.com", Phone: "+92 305 7788990", website: "www.cybersecurity.com" }] },
    { id: 7, Title: "Artificial Intelligence & Deep Learning", tag_line: "“Master AI Concepts”", A_UsPara: "Dive into AI fundamentals, neural networks, and deep learning frameworks to build intelligent applications.", Course_Info: [{ Duration: "6 Months", Mode: "Online", Skill_Level: "Advanced", Tools: "Python, TensorFlow, PyTorch" }], Facilities: ["Lab Projects", "AI Challenges", "Mentor Support"], Achievements: ["AI Projects", "Deep Learning Models", "Industry Ready"], Contact_Info: [{ Email: "info@aicourses.com", Phone: "+92 306 9988776", website: "www.aicourses.com" }] }
];

// &&&&&&&&&&&& *TUTORS DATA* &&&&&&&&&&&& \\

/* ================================
   TUTORS List & Links
================================ */
export const Tutors = [
    { TutorName: "Ali Khan", id: 1 },
    { TutorName: "Bilal Ahmed", id: 2 },
    { TutorName: "Hassan Raza", id: 3 },
    { TutorName: "Omar Malik", id: 4 },
    { TutorName: "Fahad Iqbal", id: 5 },
    { TutorName: "Usman Khan", id: 6 },
    { TutorName: "Omar Farooq", id: 7 }
];

// ========================================
// TUTORS CARD DATA
// ========================================
export const TutorCardDta = [
    { img: "https://images.pexels.com/photos/3184612/pexels-photo-3184612.jpeg", InstName: "Ali Khan", Desc: "Expert in Mathematics and Physics for high school and college students.", id: "1", btn_txt: "Contact Tutor" },
    { img: "https://images.pexels.com/photos/3184612/pexels-photo-3184612.jpeg", InstName: "Bilal Ahmed", Desc: "Specializes in English Literature and Writing Skills for all levels.", id: "2", btn_txt: "Contact Tutor" },
    { img: "https://images.pexels.com/photos/3184612/pexels-photo-3184612.jpeg", InstName: "Hassan Raza", Desc: "Professional Computer Science tutor with experience in coding and algorithms.", id: "3", btn_txt: "Contact Tutor" },
    { img: "https://images.pexels.com/photos/3184612/pexels-photo-3184612.jpeg", InstName: "Omar Malik", Desc: "Chemistry and Biology tutor with practical lab guidance for students.", id: "4", btn_txt: "Contact Tutor" },
    { img: "https://images.pexels.com/photos/3184612/pexels-photo-3184612.jpeg", InstName: "Fahad Iqbal", Desc: "Experienced in teaching History and Social Studies for middle & high school.", id: "5", btn_txt: "Contact Tutor" },
    { img: "https://images.pexels.com/photos/3184612/pexels-photo-3184612.jpeg", InstName: "Usman Khan", Desc: "Mathematics and Statistics tutor with focus on problem-solving skills.", id: "6", btn_txt: "Contact Tutor" },
    { img: "https://images.pexels.com/photos/3184612/pexels-photo-3184612.jpeg", InstName: "Omar Farooq", Desc: "Physics and Engineering tutor, specialized in practical experiments and theory.", id: "7", btn_txt: "Contact Tutor" }
];

// ========================================
// TUTORS DETAILS ARRAY
// ========================================
export const Tutors_Details = [
    { id: 1, Name: "Ali Khan", img: "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg", tag_line: "“Making Complex Concepts Simple”", About: "Ali Khan has 10+ years of experience teaching Mathematics and Physics to high school and college students, making learning interactive and effective.", Expertise: ["Mathematics", "Physics", "Calculus", "Algebra"], Achievements: ["Top Rated Tutor 2023", "Published Math Workbook", "Student Olympiad Mentor"], Contact_Info: [{ Email: "ali.khan@tutors.com", Phone: "+92 300 1234567", website: "www.alikhan-tutor.com" }] },
    { id: 2, Name: "Bilal Ahmed", img: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg", tag_line: "“Inspiring Excellence in Literature”", About: "Bilal Ahmed specializes in English Literature and creative writing, helping students improve comprehension, vocabulary, and essay writing.", Expertise: ["English Literature", "Creative Writing", "Grammar", "Essay Skills"], Achievements: ["Published Author", "Writing Competition Mentor", "Top Student Feedback"], Contact_Info: [{ Email: "bilal.ahmed@tutors.com", Phone: "+92 301 2345678", website: "www.bilalahmed-tutor.com" }] },
    { id: 3, Name: "Hassan Raza", img: "https://images.pexels.com/photos/614909/pexels-photo-614909.jpeg", tag_line: "“Coding Made Easy”", About: "Hassan Raza is a professional Computer Science tutor teaching programming, algorithms, and software development for beginners to advanced students.", Expertise: ["Programming", "Algorithms", "Data Structures", "Web Development"], Achievements: ["Developed Coding Bootcamp", "Mentored 200+ Students", "Hackathon Winner"], Contact_Info: [{ Email: "hassan.raza@tutors.com", Phone: "+92 302 3456789", website: "www.hassanraza-tutor.com" }] },
    { id: 4, Name: "Omar Malik", img: "https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg", tag_line: "“Bringing Science to Life”", About: "Omar Malik teaches Chemistry and Biology with practical lab experience and interactive lessons for better understanding.", Expertise: ["Chemistry", "Biology", "Lab Experiments", "Science Projects"], Achievements: ["Science Fair Mentor", "Published Lab Manuals", "Award-Winning Teaching Methods"], Contact_Info: [{ Email: "omar.malik@tutors.com", Phone: "+92 303 4567890", website: "www.omarmalik-tutor.com" }] },
    { id: 5, Name: "Fahad Iqbal", img: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg", tag_line: "“History Through Stories”", About: "Fahad Iqbal makes History and Social Studies engaging by connecting events with stories and modern examples.", Expertise: ["History", "Social Studies", "Civics", "World History"], Achievements: ["Historical Documentary Contributor", "Top Tutor Rating 2022", "Student Engagement Award"], Contact_Info: [{ Email: "fahad.iqbal@tutors.com", Phone: "+92 304 5678901", website: "www.fahadiqbal-tutor.com" }] },
    { id: 6, Name: "Usman Khan", img: "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg", tag_line: "“Math Simplified”", About: "Usman Khan focuses on making Mathematics and Statistics easy to understand with practical examples and problem-solving techniques.", Expertise: ["Mathematics", "Statistics", "Probability", "Algebra"], Achievements: ["Published Math Exercises", "Top Rated Online Tutor", "Mentored Students for Competitions"], Contact_Info: [{ Email: "usman.khan@tutors.com", Phone: "+92 305 6789012", website: "www.usmankhan-tutor.com" }] },
    { id: 7, Name: "Omar Farooq", img: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg", tag_line: "“Physics Made Fun”", About: "Omar Farooq teaches Physics and Engineering concepts with practical demonstrations and hands-on experiments.", Expertise: ["Physics", "Engineering", "Mechanics", "Electronics"], Achievements: ["Physics Olympiad Mentor", "Developed Learning Kits", "Published Tutorials"], Contact_Info: [{ Email: "omar.farooq@tutors.com", Phone: "+92 306 7890123", website: "www.omarfarooq-tutor.com" }] }
];

// &&&&&&&&&&&& *ONLINE TRAINING DATA* &&&&&&&&&&&& \\

/* ================================
   ONLINE TRAININGS List & Links
================================ */
export const OnlineTrainings = [
    { TrainingName: "Full Stack Web Development", id: 1 },
    { TrainingName: "Digital Marketing Mastery", id: 2 },
    { TrainingName: "Graphic Design & UX/UI", id: 3 },
    { TrainingName: "Data Science & Analytics", id: 4 },
    { TrainingName: "Cyber Security Essentials", id: 5 },
    { TrainingName: "Artificial Intelligence & ML", id: 6 },
    { TrainingName: "Project Management Professional", id: 7 }
];

// ========================================
// ONLINE TRAINING CARD DATA
// ========================================
export const OnlineTrainingCardDta = [
    { img: "https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg", InstName: "Full Stack Web Development", Desc: "Comprehensive training on front-end, back-end, and deployment of web applications.", id: "1", btn_txt: "Enroll Now" },
    { img: "https://images.pexels.com/photos/374074/pexels-photo-374074.jpeg", InstName: "Digital Marketing Mastery", Desc: "Learn SEO, social media marketing, and paid advertising to grow businesses online.", id: "2", btn_txt: "Enroll Now" },
    { img: "https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg", InstName: "Graphic Design & UX/UI", Desc: "Design stunning graphics, websites, and mobile apps with creative tools and UX principles.", id: "3", btn_txt: "Enroll Now" },
    { img: "https://images.pexels.com/photos/590022/pexels-photo-590022.jpeg", InstName: "Data Science & Analytics", Desc: "Master Python, R, SQL, and visualization to analyze and interpret complex datasets.", id: "4", btn_txt: "Enroll Now" },
    { img: "https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg", InstName: "Cyber Security Essentials", Desc: "Protect systems and data by learning the fundamentals of cyber security and ethical hacking.", id: "5", btn_txt: "Enroll Now" },
    { img: "https://images.pexels.com/photos/374074/pexels-photo-374074.jpeg", InstName: "Artificial Intelligence & ML", Desc: "Learn AI and Machine Learning algorithms, model building, and practical applications.", id: "6", btn_txt: "Enroll Now" },
    { img: "https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg", InstName: "Project Management Professional", Desc: "Develop project management skills, Agile, Scrum, and leadership to manage successful projects.", id: "7", btn_txt: "Enroll Now" }
];

// ========================================
// ONLINE TRAINING DETAILS ARRAY
// ========================================
export const OnlineTraining_Details = [
    { id: 1, Title: "Full Stack Web Development", tag_line: "“Build Modern Web Applications from Scratch”", About: "This training covers HTML, CSS, JavaScript, Node.js, React, databases, and deployment practices to create full-fledged web applications.", Modules: ["Front-end Development", "Back-end Development", "Databases & APIs", "Deployment & Hosting"], Achievements: ["Real-world Projects", "Portfolio-ready Skills", "Job Assistance"], Contact_Info: [{ Email: "fullstack@onlinetraining.com", Phone: "+92 300 1112233", website: "www.fullstacktraining.com" }] },
    { id: 2, Title: "Digital Marketing Mastery", tag_line: "“Grow Businesses with Modern Marketing Skills”", About: "Learn all aspects of digital marketing including SEO, social media, email marketing, and paid campaigns to boost online presence.", Modules: ["SEO", "Social Media Marketing", "PPC Advertising", "Email Marketing"], Achievements: ["Live Campaign Projects", "Certification of Completion", "Marketing Strategy Portfolio"], Contact_Info: [{ Email: "digital@onlinetraining.com", Phone: "+92 301 2223344", website: "www.digitalmarketingtraining.com" }] },
    { id: 3, Title: "Graphic Design & UX/UI", tag_line: "“Design Creative Interfaces & Graphics”", About: "This course teaches Adobe Photoshop, Illustrator, Figma, and UX/UI principles to design beautiful graphics and interfaces.", Modules: ["Graphic Design Tools", "UX/UI Principles", "Wireframing & Prototyping", "Portfolio Projects"], Achievements: ["Portfolio-ready Designs", "Creative Skill Development", "Professional Mentorship"], Contact_Info: [{ Email: "design@onlinetraining.com", Phone: "+92 302 3334455", website: "www.graphicdesigntraining.com" }] },
    { id: 4, Title: "Data Science & Analytics", tag_line: "“Unlock Insights from Complex Data”", About: "Learn Python, R, SQL, and data visualization to analyze and interpret data and make informed business decisions.", Modules: ["Python & R Programming", "Data Analysis", "Visualization Tools", "Machine Learning Basics"], Achievements: ["Data-driven Projects", "Certification & Portfolio", "Job-ready Skills"], Contact_Info: [{ Email: "datascience@onlinetraining.com", Phone: "+92 303 4445566", website: "www.datasciencetraining.com" }] },
    { id: 5, Title: "Cyber Security Essentials", tag_line: "“Protect Systems and Data from Threats”", About: "This training covers network security, ethical hacking, and threat analysis to secure digital systems.", Modules: ["Network Security", "Ethical Hacking", "Threat Analysis", "Cyber Law Basics"], Achievements: ["Hands-on Labs", "Security Certifications", "Practical Knowledge"], Contact_Info: [{ Email: "cybersecurity@onlinetraining.com", Phone: "+92 304 5556677", website: "www.cybersecuritytraining.com" }] },
    { id: 6, Title: "Artificial Intelligence & ML", tag_line: "“Learn AI and Machine Learning for Real-world Applications”", About: "Master AI concepts, machine learning algorithms, and model building to solve practical problems in different domains.", Modules: ["AI Fundamentals", "Machine Learning Models", "Neural Networks", "Project Implementation"], Achievements: ["AI Projects Portfolio", "Job Support", "Industry-recognized Certification"], Contact_Info: [{ Email: "ai@onlinetraining.com", Phone: "+92 305 6667788", website: "www.aitraining.com" }] },
    { id: 7, Title: "Project Management Professional", tag_line: "“Manage Projects Effectively & Efficiently”", About: "Learn project management frameworks, Agile, Scrum, risk management, and leadership to successfully manage projects.", Modules: ["Project Planning", "Agile & Scrum", "Risk Management", "Leadership Skills"], Achievements: ["PMP Certification Preparation", "Real Project Exercises", "Career Support"], Contact_Info: [{ Email: "pmp@onlinetraining.com", Phone: "+92 306 7778899", website: "www.pmponlinetraining.com" }] }
];

